routes:
  /:
    template: index
  /about/:
    data: page.about
    template: page
  /contact/:
    data: page.contact
    template: page
  /support/:
    data: page.support
    template: page-support
  /photos/:
    data: page.photos
    template: page
  /education/:
    data: page.education
    template: page
  /education/lizard-camp/:
    data: page.lizard-camp
    template: page
  /education/netp/:
    data: page.netp
    template: page
  /research/:
    data: page.research
    template: page
  /research/social-systems/:
    data: page.social-systems
    template: page
  /research/movement-ecology/:
    data: page.movement-ecology
    template: page
  /research/italian-wall-lizards/:
    data: page.italian-wall-lizards
    template: page
  /research/publications/:
    data: page.publications
    template: page
  /about/meet-the-team/:
    data: page.meet-the-team
    template: page
  /about/newsletter-archive/:
    data: page.newsletter-archive
    template: page-newsletter-archive

collections:
  /blog/:
    permalink: /blog/{slug}/
    template: post

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
